### ISSUE TITLE
GMaps canvas not rendering

### ISSUE THREAD

**Issue by stevenkhong** [sg-dotnet/website#1]
Hello team, chanced upon this today, I believe this is the right place:

<img width="1382" alt="Screenshot 2019-04-23 at 11 25 51 AM" src="https://user-images.githubusercontent.com/6249166/56551390-e0b82e00-65ba-11e9-9d0e-64421f706092.png">

**Comment by goh-chunlin** [comment]
Sorry for the late reply, @stevenkhong !

We totally missed this Issue out but we had corrected it.

I had also changed the website layout now.
